---

- hosts: 46.101.153.180
  remote_user: root
  tasks:
  - user: name=rgu comment="Ruby Guru" #group=sudo
  - name: install software
    apt: pkg=mongodb,mc,nodejs,build-essential,npm,nginx,htop state=latest
    notify:
    - restart mongodb
    - restart nginx
  - name: ensure mongodb and nginx are running (and enable it at boot)
    service: name=mongodb state=started enabled=yes
    service: name=nginx state=started enabled=yes
  handlers:
    - name: restart mongodb
      service: name=mongodb state=restarted
    - name: restart nginx
      service: name=nginx state=restarted

