source 'https://rubygems.org'

ruby '2.2.2'

gem 'rails', '4.2.1'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'less-rails'
gem 'jquery-rails'
gem 'jbuilder', '~> 2.0'
gem 'bootstrap-sass'
gem 'high_voltage'
gem 'simple_form'
gem 'slim-rails'
gem 'mongoid', '~> 4.0.2'
gem 'google-api-client', '~> 0.8.6'
gem 'pry'
gem 'therubyracer'

group :development do
  gem 'better_errors'
  gem 'haml2slim'
  gem 'html2haml'
  gem 'quiet_assets'
  gem 'rails_apps_pages'
  gem 'rails_layout'
  gem 'web-console', '~> 2.0'
end

group :development, :test do
  gem 'pry-rails'
  gem 'pry-rescue'
  gem 'thin'
end

group :production do
  gem 'unicorn'
end
